### ISSUE TITLE
Don't return updates and draws

### ISSUE THREAD

**Issue by MrTanoshii** [MrTanoshii/PyWeek-35#11]
https://github.com/MrTanoshii/PyWeek-35/blob/b64fa84c66d4298c1c2a513c7fcc2bd41fd70cc7/src/classes/windows/game.py#L41

https://github.com/MrTanoshii/PyWeek-35/blob/b64fa84c66d4298c1c2a513c7fcc2bd41fd70cc7/src/classes/windows/game.py#L45

**Comment by IrrationalBoolean** [comment]
sure thing boss man. 😉 💯
